# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop' 

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/RecipesDatabase_Create.sql'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true

- task: SqlAzureDacpacDeployment@1
  inputs:
    ConnectedServiceNameARM: 'Visual Studio Enterprise (2dac1c43-b88c-412f-8b6c-89295fe465de)'
    ServerName: 'rkfunctionsqlserver-hlzdrcz6kjmso.database.windows.net'
    DatabaseName: 'rkfunctiondb'
    SqlUsername: 'sqladmin'
    SqlPassword: 'Password007'
    TaskNameSelector: 'SqlTask'
    DacpacFile: '$(agent.releaseDirectory)\RecipesDatabase.dacpac'
    SqlFile: '$(build.artifactstagingdirectory)\RecipesDatabase_Create.sql'

- task: CmdLine@2
  inputs:
    script: 'dir'